// AUTO-GENERATED từ file 5_PFMEA_DPC_G823_ver_1.xlsx — seed PFMEA cho model base G823.
// Ảnh hưởng chỉ chứa mô tả; câu tiêu chí nghiêm trọng (=>) được thêm khi người dùng chọn ở dropdown.
import type { SeedModel } from "./seedTypes";

export const G823_SEED: SeedModel = {
  key: "G823",
  steps: [
    {
      processStep: "1. Kiểm tra phôi đầu vào",
      fn: "Chuẩn bị sản xuất",
      failureModes: [
        {
          requirement: "Kiểm tra chủng loại: đúng chủng loại",
          failureMode: "Sai chủng loại",
          effect: "Phải thay đổi kế hoạch sản xuất",
          severity: 2,
          classification: "",
          causes: ["Không kiểm tra mã linh kiện khi nhập"],
        },
        {
          requirement: "Kiểm tra số lượng: đủ số lượng",
          failureMode: "Thiếu số lượng",
          effect: "Phải nhập thêm số lượng",
          severity: 2,
          classification: "",
          causes: ["Không kiểm tra số lượng linh kiện khi nhập"],
        },
      ],
    },
    {
      processStep: "2. Hàn Cap",
      fn: "Liên kết giữa damper cap và main pipe",
      failureModes: [
        {
          requirement: "Kích thước chiều cao tổng, từ mặt dưới cap đến mặt đầu mainpipe & độ xâm nhập hàn đạt theo bản vẽ",
          failureMode: "Kích thước chiều cao tổng không đạt / -Kích thước từ mặt dưới cap đến mặt đầu mainpipe không đạt / -Độ xâm nhập hàn không đạt",
          effect: "Lệch 2 bên giảm xóc",
          severity: 5,
          classification: "",
          causes: ["Cài đặt điện áp hàn không đúng tiêu chuẩn", "Điện áp không đạt do tụ điện bị hỏng", "Hết dầu bôi trơn cho xylanh điện cực", "Áp lực khí vào không đạt", "Xylanh điện cực trên bị kẹt"],
        },
        {
          requirement: "Độ vuông góc đạt theo bản vẽ",
          failureMode: "Độ vuông góc không đạt",
          effect: "Giảm xóc bị nghiêng",
          severity: 5,
          classification: "",
          causes: ["Điện cực, đồ gá hàn bị va đập, nứt vỡ, rơ lỏng", "Điện cực bị mòn", "Xylanh điện cực dưới bị kẹt"],
        },
        {
          requirement: "Đường kính vùng trượt đạt theo bản vẽ",
          failureMode: "Đường kính vùng trượt không đạt",
          effect: "Giảm xóc bị kẹt",
          severity: 6,
          classification: "",
          causes: ["Nhân viên lắp điện cực dưới bị lệch tâm, kẹp vào mainpipe bị lệch gây móp méo mainpipe"],
        },
        {
          requirement: "Độ bền kéo (độ bền mối hàn) đạt theo bản vẽ",
          failureMode: "Độ bền mối hàn không đạt",
          effect: "Mối hàn bị bung→tuột cụm giảm xóc",
          severity: 9,
          classification: "S",
          causes: ["Cài đặt điện áp hàn không đúng tiêu chuẩn", "Điện áp không đạt do tụ điện bị hỏng", "Cài đặt gia áp điện cực không đúng tiêu chuẩn", "Chỉnh độ nhô của mainpipe chưa đúng", "Điện cực bị mòn", "Để lẫn sản phẩm NG vào sản phẩm OK"],
        },
        {
          requirement: "Mối hàn không bị vỡ trong kiểm tra phá hủy",
          failureMode: "Mối hàn bị vỡ khi kiểm tra phá hủy",
          effect: "Nguy cơ gãy mối hàn",
          severity: 8,
          classification: "",
          causes: ["Biến động trong quá trình hàn"],
        },
        {
          requirement: "Mối hàn được hàn tròn kín xung quanh, có vết chảy vật liệu, không nứt/cháy thủng/bavia",
          failureMode: "Mối hàn không được hàn kín xung quanh, không có vết chảy vật liệu, có vết nứt, cháy thủng và bavia",
          effect: "Chảy dầu",
          severity: 7,
          classification: "",
          causes: ["Biến động trong quá trình hàn"],
        },
        {
          requirement: "Mặt ngoài: không xước, xỉ hàn, va đập, bavia, bất thường, rỉ trên bề mặt và lòng trong",
          failureMode: "Mặt ngoài: có xước, xỉ hàn, va đập, bavia, bất thường, rỉ trên bề mặt và lòng trong chi tiết",
          effect: "Có lỗi mặt ngoài hoặc tiếng kêu, có thể thao tác xe được, có điểm không phù hợp trên sản phẩm mà hầu hết khách hàng (hơn 75%) nhận ra",
          severity: 4,
          classification: "",
          causes: ["Xỉ hàn bắn vào sản phẩm"],
        },
      ],
    },
    {
      processStep: "3. Hàn Joint",
      fn: "Liên kết giữa Joint metal và cụm Mainpipe comp",
      failureModes: [
        {
          requirement: "Kích thước chiều cao tổng, từ tâm Joint metal đến mặt trên Damper cap & độ xâm nhập hàn đạt theo bản vẽ",
          failureMode: "Kích thước chiều cao tổng không đạt / -Kích thước từ tâm Joint metal đến mặt trên Damper ca không đạt / -Độ xâm nhập hàn không đạt",
          effect: "Lệch 2 bên giảm xóc",
          severity: 5,
          classification: "",
          causes: ["Biến động trong quá trình hàn", "Đồ gá bị mòn", "Xylanh điện cực trên bị kẹt", "Hết dầu bôi trơn cho xylanh điện cực", "Áp lực khí vào không đạt", "Để lẫn hàng NG vào hàng OK"],
        },
        {
          requirement: "Độ đối xứng X, Y đạt theo bản vẽ",
          failureMode: "Độ đối xứng X, Y không đạt",
          effect: "Giảm xóc bị lệch",
          severity: 5,
          classification: "",
          causes: ["Biến động trong quá trình hàn", "Điện cực, đồ gá rơ lỏng"],
        },
        {
          requirement: "Đường kính vùng trượt đạt theo bản vẽ",
          failureMode: "Đường kính vùng trượt không đạt",
          effect: "Giảm xóc bị kẹt",
          severity: 6,
          classification: "",
          causes: ["Biến động trong quá trình hàn", "Xylanh điện cực dưới bị kẹt"],
        },
        {
          requirement: "Độ bền kéo (độ bền mối hàn) đạt theo bản vẽ",
          failureMode: "Độ bền mối hàn không đạt",
          effect: "Mối hàn bị bung→tuột cụm giảm xóc",
          severity: 9,
          classification: "S",
          causes: ["Biến động trong quá trình hàn", "Cài đặt sai dòng điện hàn, thời gian hàn, độ nhún", "Cài đặt sai gia áp điện cực", "Chỉnh độ nhô của mainpipe chưa đúng", "Điện cực bị mòn"],
        },
        {
          requirement: "Mối hàn không bị vỡ trong kiểm tra phá hủy",
          failureMode: "Mối hàn bị vỡ khi kiểm tra phá hủy",
          effect: "Nguy cơ gãy mối hàn",
          severity: 8,
          classification: "",
          causes: ["Biến động trong quá trình hàn"],
        },
        {
          requirement: "Mặt ngoài: không xước, xỉ hàn, va đập, bavia, bất thường, rỉ trên bề mặt và lòng trong",
          failureMode: "Mặt ngoài: có xước, xỉ hàn, va đập, bavia, bất thường, rỉ trên bề mặt và lòng trong chi tiết",
          effect: "Có lỗi mặt ngoài hoặc tiếng kêu, có thể thao tác xe được, có điểm không phù hợp trên sản phẩm mà hầu hết khách hàng (hơn 75%) nhận ra",
          severity: 4,
          classification: "",
          causes: ["Xỉ hàn bắn vào sản phẩm"],
        },
      ],
    },
    {
      processStep: "Đóng dấu",
      fn: "Hiển thị ngày tháng năm sản xuất",
      failureModes: [
        {
          requirement: "Đầy đủ 2 dấu",
          failureMode: "Thiếu dấu",
          effect: "Không biết được ngày tháng năm sản xuất",
          severity: 1,
          classification: "",
          causes: ["Gá thiếu con dấu"],
        },
        {
          requirement: "Dấu rõ nét",
          failureMode: "Dấu không rõ nét",
          effect: "Không biết được ngày tháng năm sản xuất",
          severity: 1,
          classification: "",
          causes: ["Áp lực khí nguồn và áp lực đóng dấu không đạt"],
        },
      ],
    },
    {
      processStep: "4. Hàn gia cường",
      fn: "Hàn gia cường (補強溶接)",
      failureModes: [
        {
          requirement: "Độ bền kéo đạt theo bản vẽ; chất lượng mối hàn theo SPEC 20209-AAY-0-00",
          failureMode: "Độ bền mối hàn không đạt / (Mối hàn bị phá hủy khi kiểm tra độ bền) / Các hạng mục chất lượng mối hàn khác không đạt theo SPEC: 20209-AAY-0 -00",
          effect: "Nghiêng joint metal",
          severity: 8,
          classification: "S",
          causes: ["Cài đặt, điều chỉnh điều kiện hàn chưa đúng: / -Dòng điện, Điện áp, Lưu lượng khí C02, Góc tay hàn, Lượng nhô của dây hàn", "Cài đặt tốc độ hàn, thời gian hàn chưa đúng", "SPEC dây hàn chưa đúng", "Khí CO2 có tỉ lệ không đúng", "Tắc bép hàn (lượng khí ít)", "Bép hàn bị mòn"],
        },
        {
          requirement: "Chiều dài mối hàn đạt theo bản vẽ",
          failureMode: "Chiều dài mối hàn không đạt",
          effect: "Độ bền mối hàn thấp, cụm giảm xóc bị yếu",
          severity: 8,
          classification: "",
          causes: ["Cài đặt tốc độ hàn, thời gian hàn chưa đúng", "Cài đặt, điều chỉnh điều kiện hàn chưa đúng: / -Dòng điện, Điện áp, Lưu lượng khí C02, Góc tay hàn, Lượng nhô của dây hàn"],
        },
        {
          requirement: "Linh kiện phải được hàn gia cường",
          failureMode: "Linh kiện chưa được hàn gia cường",
          effect: "Nghiêng joint metal, cụm giảm xóc bị kẹt",
          severity: 8,
          classification: "",
          causes: ["Bỏ lọt công đoạn hàn gia cường"],
        },
      ],
    },
    {
      processStep: "5. Kiểm tra dò khí",
      fn: "Kiểm tra các mối hàn xem có bị hở không",
      failureModes: [
        {
          requirement: "Kiểm tra dò rỉ khí: không dò rỉ khí tại áp suất 490 kPa",
          failureMode: "Bỏ lọt sản phẩm bị dò rỉ khí tại áp suất 490 kPa",
          effect: "Nguy cơ dò rỉ dầu",
          severity: 7,
          classification: "",
          causes: ["Áp lực khí nguồn, khí thổi, khí kẹp không đạt", "Thời gian dò khí quá ít", "Mức nước không ngập sản phẩm", "Đầu thổi khí bị tắc", "Đồ gá, đầu bịt bị nứt, vỡ, biến dạng, rơ lỏng"],
        },
        {
          requirement: "Bề mặt mối hàn được hàn tròn kín xung quanh, có vết chảy vật liệu, không nứt/cháy thủng/bavia",
          failureMode: "Sản phẩm không được hàn tròn kín xung quanh, không có vết chảy vật liệu, có vết nứt, vết cháy thủng và bavia",
          effect: "Nguy cơ dò rỉ dầu",
          severity: 7,
          classification: "",
          causes: ["Sản phẩm NG từ công đoạn trước bị lưu suất"],
        },
        {
          requirement: "Mặt ngoài: không xước, xỉ hàn, va đập, bất thường",
          failureMode: "Sản phẩm xước bề mặt ngoài, có xỉ hàn, va đập, bất thường",
          effect: "Có lỗi mặt ngoài hoặc tiếng kêu, có thể thao tác xe được, có điểm không phù hợp trên sản phẩm mà hầu hết khách hàng (hơn 75%) nhận ra",
          severity: 4,
          classification: "",
          causes: ["Sản phẩm NG từ công đoạn trước bị lưu suất"],
        },
        {
          requirement: "Mặt ngoài và lòng trong: không bị rỉ",
          failureMode: "Sản phẩm bị rỉ trên bề mặt  và lòng trong chi tiết",
          effect: "Có lỗi mặt ngoài hoặc tiếng kêu, có thể thao tác xe được, có điểm không phù hợp trên sản phẩm mà hầu hết khách hàng (hơn 75%) nhận ra",
          severity: 4,
          classification: "",
          causes: ["Nồng độ dầu chống rỉ không đạt"],
        },
      ],
    },
  ],
};
